SOURCES += ./src/main.c
SOURCES += ./src/builtins/cd.c
SOURCES += ./src/builtins/echo.c
SOURCES += ./src/builtins/env.c
SOURCES += ./src/builtins/exit.c
SOURCES += ./src/builtins/export.c
SOURCES += ./src/builtins/pwd.c
SOURCES += ./src/builtins/unset.c
# SOURCES += ./src/executor/executor.c
# SOURCES += ./src/executor/io.c
# SOURCES += ./src/lexer/lexer.c
# SOURCES += ./src/lexer/quotes.c
# SOURCES += ./src/lexer/lexer_list/lex_add_after.c
# SOURCES += ./src/lexer/lexer_list/lex_add_back.c
# SOURCES += ./src/lexer/lexer_list/lex_add_before.c
# SOURCES += ./src/lexer/lexer_list/lex_clear.c
# SOURCES += ./src/lexer/lexer_list/lex_geti.c
# SOURCES += ./src/lexer/lexer_list/lex_last.c
# SOURCES += ./src/lexer/lexer_list/lex_malloc_check.c
# SOURCES += ./src/lexer/lexer_list/lex_new.c
